{% set name = "dsub" %}
{% set version = "0.4.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3190100c5d227c55571fb891be433541d2d156cbadf9f73df15578de83635d5a

build:
  number: 0
  skip: true  # [not unix]
  entry_points:
    - dsub=dsub.commands.dsub:main
    - dstat=dsub.commands.dstat:main
    - ddel=dsub.commands.ddel:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - google-api-python-client
    - google-auth
    - pip
    - python
    - python-dateutil
    - pytz
    - pyyaml >=3.12
    - retrying
    - six
    - tabulate
  run:
    - google-api-python-client
    - google-auth
    - python
    - python-dateutil
    - pytz
    - pyyaml >=3.12
    - retrying
    - six
    - tabulate

test:
  imports:
    - dsub
    - dsub.commands
    - dsub.lib
    - dsub.providers
  commands:
    - dsub --help
    - dstat --help
    - ddel --help

about:
  home: https://github.com/DataBiosphere/dsub
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: A command-line tool that makes it easy to submit and run batch scripts in the cloud
  doc_url: https://github.com/DataBiosphere/dsub
  dev_url: https://github.com/DataBiosphere/dsub

extra:
  recipe-maintainers:
    - notestaff
