travis:
  secure:
    BINSTAR_TOKEN: buMrTwoL6RLAhsB1Zs6RcJLIgnrHbXDtKvdTUIyAs87Mcz+YTANruxkhaIXy9p9Zwn6PyrhEFnMwKoAA5B+UlCHnXPUP9/OQ+I4kpxmh13oPLydQf4XvRYevhDVaEk10n5bI05+hLwntSeUwTOZYPPr7xhsH/X6Ri0gdmyFMllaU9l/ooXhFDDAgkwrksqpvyDcha6xvWsJGiHM8MYpxbJzSTy2Pp56CfeKKvT6Y3WUSOckeaCEoK13+t4+fTfFTfUZ07s9m/FTJVd08XIDIcsHiqm2XuRV7Tfsd4Tm34A75oIK7QDIfiNvBTljo2ytvz0zDgsh8dUIKgT1bETc9QtkMAcA3q/UtfQBFzSD0jcW8eakYQ3TBUd/70XOo2dS6L5CsSFR92u0zchJPqqr0+DzKjuXvRT5uLxlzzlWzopLm6T4MsIgvwGu+t3ey+3CaF9wj7nKulHzJxXnMqaHOPez2jDfAJu+/u0kw/lwVcN00vdhyOoDlaAyU88TYrCVUNH/Zlr7326AVi13cKpnAUN0U+KSc7RwDB37Ff5fKu5IeqXEWmW1j/OO3CnFFw6F0Mhj21mNLMKRUT43+ZojalKn6nBpT+itNtwLCH+mgNmQkJ6R/MoFqHWtPID3mBbywkmomoX9dfToa6rOSuXt9Nid1iugsC5a7Q3CCZJyPxj4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
